vich_uploader:
    db_driver: orm # or mongodb or phpcr - default db driver
    twig: true # set to false to disable twig integration
    form: true # set to false to disable form integration
    storage: file_system # or gaufrette or flysystem

    metadata:
        type: attribute
        auto_detection: true
        cache: file

    mappings:
        recette_images:
            uri_prefix: '%recette_images%'
            upload_destination: "%kernel.project_dir%/public%recette_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
